import { formatEnum } from '@hms/shared';

const LABELS: Record<string, string> = {
  'auth.login': 'Signed in',
  'auth.logout': 'Signed out',
  'auth.password_change': 'Changed password',
  'auth.refresh_reuse_detected': 'Reused session token blocked',
  'patient.create': 'Registered patient',
  'patient.update': 'Updated patient details',
  'patient.view_timeline': 'Viewed patient timeline',
  'patient.view_clinical_summary': 'Viewed clinical summary',
  'patient.emergency_access': 'Used emergency record access',
  'medical_history.create': 'Added medical history',
  'medical_history.amend': 'Amended medical history',
  'document.upload': 'Uploaded document',
  'document.view': 'Opened document',
  'document.void': 'Voided document',
  'appointment.create': 'Booked appointment',
  'appointment.reschedule': 'Rescheduled appointment',
  'appointment.update': 'Updated appointment',
  'appointment.confirmed': 'Confirmed appointment',
  'appointment.cancelled': 'Cancelled appointment',
  'appointment.no_show': 'Marked appointment as no-show',
  'appointment.checked_in': 'Checked in appointment',
  'appointment.in_consultation': 'Sent patient to doctor',
  'appointment.completed': 'Completed appointment',
  'token.walk_in': 'Issued walk-in token',
  'token.check_in': 'Issued token for appointment',
  'token.call': 'Called patient in',
  'token.complete': 'Completed visit',
  'token.skip': 'Skipped token',
  'token.requeue': 'Returned token to queue',
  'token.cancel': 'Cancelled token',
  'token.vitals': 'Recorded vitals',
  'consultation.create': 'Started consultation',
  'consultation.update': 'Saved consultation draft',
  'consultation.complete': 'Completed consultation',
  'consultation.addendum': 'Added consultation addendum',
  'prescription.create': 'Issued prescription',
  'prescription.cancel': 'Cancelled prescription',
  'referral.create': 'Created referral',
  'charge.create': 'Added charge',
  'charge.void': 'Voided charge',
  'invoice.create': 'Created invoice',
  'invoice.payment': 'Recorded payment',
  'invoice.refund': 'Recorded refund',
  'invoice.cancel': 'Cancelled invoice',
  'service.create': 'Added price list item',
  'service.update': 'Updated price list item',
  'medicine.create': 'Added medicine',
  'medicine.update': 'Updated medicine',
  'inventory.stock_in': 'Received stock',
  'inventory.adjustment': 'Adjusted stock',
  'inventory.write_off': 'Wrote off stock',
  'inventory.return': 'Returned stock',
  'pharmacy.dispense': 'Dispensed medicines',
  'lab_test.create': 'Added lab test',
  'lab_test.update': 'Updated lab test',
  'lab_order.create': 'Ordered lab tests',
  'lab_order.sample_collected': 'Collected sample',
  'lab_order.processing': 'Started lab processing',
  'lab_order.results_entered': 'Entered lab results',
  'lab_order.verified': 'Verified lab results',
  'lab_order.released': 'Released lab report',
  'lab_order.amended': 'Amended lab results',
  'lab_order.cancelled': 'Cancelled lab order',
  'ward.create': 'Added ward',
  'ward.update': 'Updated ward',
  'room.create': 'Added room',
  'bed.create': 'Added bed',
  'bed.update': 'Updated bed',
  'bed.status': 'Changed bed status',
  'admission.create': 'Admitted patient',
  'admission.transfer': 'Transferred patient',
  'admission.discharge': 'Discharged patient',
  'ot.create': 'Scheduled procedure',
  'ot.update': 'Updated procedure',
  'user.create': 'Created user',
  'user.update': 'Updated user',
  'user.password_reset': 'Reset user password',
  'user.unlock': 'Unlocked user',
  'doctor.create': 'Added doctor profile',
  'doctor.update': 'Updated doctor profile',
  'settings.update': 'Changed hospital settings',
  'report.export': 'Exported report',
  'audit.export': 'Exported audit log',
};

export function auditLabel(action: string) {
  if (LABELS[action]) return LABELS[action];
  const [resource, verb] = action.split('.');
  return `${formatEnum(resource)}: ${formatEnum(verb ?? '')}`;
}
