export const ROLES = [
  'admin',
  'doctor',
  'receptionist',
  'nurse',
  'pharmacist',
  'lab_staff',
  'billing_staff',
  'management',
] as const;

export type Role = (typeof ROLES)[number];

export const ROLE_LABELS: Record<Role, string> = {
  admin: 'Administrator',
  doctor: 'Doctor',
  receptionist: 'Receptionist',
  nurse: 'Nurse',
  pharmacist: 'Pharmacist',
  lab_staff: 'Laboratory Staff',
  billing_staff: 'Billing Staff',
  management: 'Hospital Management',
};

export const PERMISSIONS = [
  'patient:read',
  'patient:create',
  'patient:update',
  'medical:read',
  'medical:write',
  'vitals:write',
  'doctor:read',
  'doctor:manage',
  'appointment:read',
  'appointment:manage',
  'queue:read',
  'queue:manage',
  'consultation:read',
  'consultation:write',
  'prescription:read',
  'prescription:write',
  'referral:read',
  'referral:write',
  'billing:read',
  'billing:manage',
  'billing:refund',
  'service:read',
  'service:manage',
  'pharmacy:read',
  'pharmacy:dispense',
  'pharmacy:inventory',
  'lab:read',
  'lab:order',
  'lab:process',
  'lab:verify',
  'lab:catalog',
  'bed:read',
  'bed:manage',
  'admission:manage',
  'ward:configure',
  'ot:read',
  'ot:manage',
  'report:read',
  'analytics:read',
  'user:read',
  'user:manage',
  'settings:manage',
  'audit:read',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const RECEPTION: Permission[] = [
  'patient:read',
  'patient:create',
  'patient:update',
  'doctor:read',
  'appointment:read',
  'appointment:manage',
  'queue:read',
  'queue:manage',
  'billing:read',
  'billing:manage',
  'service:read',
  'bed:read',
];

/**
 * Role to permission mapping. This is the single source of truth for
 * authorization and is enforced by the API. The frontend uses the same map
 * only to decide what to display.
 */
export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  admin: PERMISSIONS,
  doctor: [
    'patient:read',
    'patient:update',
    'medical:read',
    'medical:write',
    'vitals:write',
    'doctor:read',
    'appointment:read',
    'appointment:manage',
    'queue:read',
    'queue:manage',
    'consultation:read',
    'consultation:write',
    'prescription:read',
    'prescription:write',
    'referral:read',
    'referral:write',
    'service:read',
    'pharmacy:read',
    'lab:read',
    'lab:order',
    'bed:read',
    'admission:manage',
    'ot:read',
    'ot:manage',
  ],
  receptionist: RECEPTION,
  nurse: [
    'patient:read',
    'medical:read',
    'vitals:write',
    'doctor:read',
    'appointment:read',
    'queue:read',
    'queue:manage',
    'consultation:read',
    'prescription:read',
    'referral:read',
    'lab:read',
    'lab:process',
    'bed:read',
    'bed:manage',
    'admission:manage',
    'ot:read',
  ],
  pharmacist: [
    'patient:read',
    'doctor:read',
    'prescription:read',
    'pharmacy:read',
    'pharmacy:dispense',
    'pharmacy:inventory',
    'service:read',
    'report:read',
  ],
  lab_staff: [
    'patient:read',
    'doctor:read',
    'lab:read',
    'lab:process',
    'lab:verify',
    'lab:catalog',
    'service:read',
  ],
  billing_staff: [
    'patient:read',
    'doctor:read',
    'billing:read',
    'billing:manage',
    'billing:refund',
    'service:read',
    'service:manage',
    'report:read',
  ],
  management: [
    'patient:read',
    'doctor:read',
    'appointment:read',
    'queue:read',
    'billing:read',
    'service:read',
    'pharmacy:read',
    'lab:read',
    'bed:read',
    'ot:read',
    'referral:read',
    'report:read',
    'analytics:read',
    'user:read',
    'audit:read',
  ],
};

export function roleHasPermission(role: Role, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
